services:
  - type: web
    name: vitamin-flask-api
    runtime: python
    buildCommand: pip install -r vitamin/backend/requirements.txt
    startCommand: cd vitamin/backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
